rocket-team-webdev/wave

packages/client/src/reportWebVitals.js, packages/server/src/db/album-seed.js, packages/server/src/db/connect.js, packages/server/src/db/genre-seed.js, packages/server/src/db/playlist-seed.js, packages/server/src/db/seed.js, packages/server/src/db/track-seed.js, packages/server/src/db/user-seed.js, packages/server/src/index.js, packages/server/src/models/album-model.js, packages/server/src/models/genre-model.js, packages/server/src/models/index.js, packages/server/src/models/playback-model.js, packages/server/src/models/playlist-model.js, packages/server/src/models/track-model.js, packages/server/src/models/user-model.js
=> Initial config/database schema/05

README.md
- Added initial wireframes.
- Updated `README.md` with Figma file link.
Closes #2
=> Initial config/basic wireframing/02

packages/client/src/App.js, packages/client/src/pages/Public/Account/update-schema.js, packages/client/src/pages/Public/ResetPassword/reset-pass-schema.js, packages/client/src/pages/Public/SignIn/sign-in-schema.js, packages/client/src/pages/Public/SignUp/sign-up-schema.js, packages/client/src/redux/music-queue/actions.js, packages/client/src/redux/music-queue/reducer.js, packages/client/src/redux/music-queue/state.js, packages/client/src/redux/music-queue/types.js, packages/client/src/redux/reducers.js, packages/client/src/redux/user/state.js, packages/server/package.json, packages/server/src/controllers/user-controller.js
=> Tech/sprint 2/77/redux state music queue

packages/client/src/constants/local-storage.js, packages/client/src/redux/music-queue/actions.js, packages/client/src/redux/music-queue/reducer.js, packages/client/src/redux/music-queue/types.js, packages/client/src/redux/store.js
=> Music player/queue localstorage/46/main

packages/client/src/components/SongCard/SongCard.jsx, packages/client/src/pages/Public/Tracks/Tracks.jsx, packages/server/src/controllers/track-controller.js
=> Tracks management/my songs state/94/main

packages/client/src/components/MusicPlayer/MusicPlayer.jsx, packages/client/src/components/MusicPlayer/MusicPlayer.scss, packages/client/src/components/TrackCard/TrackCard.jsx
=> Music player/like track player/118/main

packages/client/src/components/ArtistCard/ArtistCard.jsx, packages/client/src/components/Button/Button.scss, packages/client/src/components/DragAndDrop/DragAndDrop.jsx, packages/client/src/components/HomeElement/HomeElement.jsx, packages/client/src/components/HomeElement/HomeElement.scss, packages/client/src/components/HomePopular/HomePopular.jsx, packages/client/src/components/Input/Input.jsx, packages/client/src/components/Input/Input.scss, packages/client/src/components/PlaylistCard/PlaylistCard.jsx, packages/client/src/components/Select/Select.jsx, packages/client/src/components/Select/Select.scss, packages/client/src/components/Spinner/Spinner.jsx, packages/client/src/components/Spinner/index.js, packages/client/src/components/TrackCard/TrackCard.jsx, packages/client/src/components/TrackCard/TrackCard.scss, packages/client/src/pages/Public/CreateAlbum/CreateAlbum.jsx, packages/client/src/pages/Public/Home/Home.jsx, packages/client/src/pages/Public/SignIn/SignIn.jsx, packages/client/src/pages/Public/SignUp/SignUp.jsx, packages/client/src/pages/Public/TrackUpdate/TrackUpdate.jsx, packages/client/src/pages/Public/TrackUpload/TrackUpload.jsx, packages/client/src/pages/Public/Tracks/Tracks.jsx, packages/client/src/sass/components/_font.scss, packages/client/src/sass/components/_globals.scss
- Improved layouts:
- SignIn (remember, sign up).
- TrackUpload (& added back button).
- TrackUpdate (& added back button).
- CreateAlbum.
- `<Select />`:
- Added `isNegative` prop.
- Added `hasAddIcon` prop.
- Switched all `<i></i>` to React icons.
- Created `<Spinner />` for loading states with `isNegative` prop.
- `<TrackCard />`:
- Add fixed width & height to image.
- Add min-width in number.
- `<Input />`:
- Fix `<Input />` type file width.
- Added `hasForgotPassword` prop.
- `<Button />`:
- Add max height to large buttons
Closes #92
=> Tech/sprint 2/92/main

packages/client/package.json, packages/client/src/components/ArtistCard/ArtistCard.jsx, packages/client/src/components/GenreCard/GenreCard.jsx, packages/client/src/components/GenreCard/index.js, packages/client/src/components/HomeElement/HomeElement.jsx, packages/client/src/components/HomeMyWave/HomeMyWave.jsx, packages/client/src/components/HomePopular/HomePopular.jsx, packages/client/src/components/JumboText/JumboText.jsx, packages/client/src/components/MusicPlayer/MusicPlayer.jsx, packages/client/src/components/PlaylistCard/PlaylistCard.jsx, packages/client/src/components/SVGicons/HeartIcon/HeartIcon.js, packages/client/src/components/SVGicons/HeartIcon/index.js, packages/client/src/components/TrackCard/TrackCard.jsx, packages/client/src/components/UserCard/UserCard.jsx, packages/client/src/pages/Public/CreateAlbum/CreateAlbum.jsx, packages/client/src/pages/Public/Home/Home.jsx, packages/client/src/pages/Public/Tracks/Tracks.jsx, packages/client/src/utils/motionSettings.js
- Added `framer-motion` dependency.
- Added `<HeartIcon />`.
- Added `<GenreCard />`
- Added `motionSettings.js` in utils.
- Added `isAnimationContainer` to `<HomeElement />`.
- Added initial animations in:
- `<GenreCard />`.
-  `<UserCard />`
- `<PlaylistCard />`.
- `<TrackCard />`.
- `<HeartIcon />`.
- `<JumboText />` (in home).
Closes #129
=> Tech/sprint 3/129/main

packages/client/src/components/TrackCard/TrackCard.jsx, packages/client/src/components/TrackList/TrackList.jsx, packages/client/src/pages/Public/Tracks/Tracks.jsx
- Added `hasSorter` prop to `<TrackList />`.
Closes #147
=> Tech/sprint 3/147/main

packages/client/src/api/playlists-api.js, packages/client/src/pages/Public/SinglePlaylist/SinglePlaylist.jsx, packages/server/src/controllers/me-controller.js, packages/server/src/controllers/playlists-controller.js, packages/server/src/controllers/search-controller.js
- Added delete playlist frontend functionality.
- Fixed delete playlist backend functionality.
Closes #160
=> Playlist management/playlist delete/160/main

packages/client/src/components/Header/Header.jsx, packages/client/src/components/HomeMyWave/HomeMyWave.jsx, packages/server/src/controllers/me-controller.js, packages/server/src/controllers/playlists-controller.js
=> Basic homepage/popular playlists in home/24/main

packages/client/src/components/BigThumbnail/BigThumbnail.jsx, packages/client/src/components/Button/Button.jsx, packages/client/src/components/Checkbox/Checkbox.jsx, packages/client/src/components/DragAndDrop/DragAndDrop.jsx, packages/client/src/components/Header/Header.scss, packages/client/src/components/Input/Input.scss, packages/client/src/components/Textarea/Textarea.jsx, packages/client/src/components/UserWave/UserWave.jsx, packages/client/src/pages/Public/CreateAlbum/CreateAlbum.jsx, packages/client/src/pages/Public/CreatePlaylist/CreatePlaylist.jsx, packages/client/src/pages/Public/PlaylistUpdate/PlaylistUpdate.jsx, packages/client/src/pages/Public/PopularAlbums/PopularAlbums.jsx, packages/client/src/pages/Public/PopularPlaylists/PopularPlaylists.jsx, packages/client/src/pages/Public/SignIn/SignIn.jsx, packages/client/src/pages/Public/TrackUpdate/TrackUpdate.jsx, packages/client/src/pages/Public/TrackUpload/TrackUpload.jsx, packages/client/src/pages/Public/UpdateAlbum/UpdateAlbum.jsx, packages/client/src/sass/components/_globals.scss, packages/server/src/controllers/me-controller.js, packages/server/src/controllers/users-controller.js
- Added col-md-7 to Keep me logged checkbox.
- Solved border radius in input color.
- Improved buttons wrappers in all upload/update forms.
- Set `<BigThumbnail />` and `<DragAndDrop />` height to 100%.
- Fixed data received from `getUserAlbums` in backend.
-  Added top padding in `<TextArea />`.
- Set two columns to popular albums & popular playlists.
- Added limit to playlist and tracks shown in `<Home />`.
- Added Spinner in all upload/update pages.
- Add weight to NavLinks in Header.
Closes #243
=> Tech/sprint 4/243/layout improvements

packages/client/src/components/TrackCard/TrackCard.jsx, packages/client/src/pages/Public/CreateAlbum/CreateAlbum.jsx
=> Tech/sprint 4/253/create button and context menu

packages/client/src/components/MusicPlayer/MusicPlayer.jsx, packages/client/src/components/TrackCard/TrackCard.jsx, packages/client/src/components/TrackCard/TrackCard.scss, packages/client/src/pages/Public/CreatePlaylist/CreatePlaylist.jsx, packages/server/src/controllers/users-controller.js
closes #248 and closes #106 and closes #256
=> Tech/sprint 4/248/add to playlist fix

packages/client/src/components/DragAndDrop/DragAndDrop.jsx, packages/client/src/components/Input/Input.jsx, packages/client/src/pages/Public/Account/Account.jsx, packages/client/src/pages/Public/Reauthenticate/Reauthenticate.jsx
=> Bugs/sprint 4/reauthenticate

packages/client/src/App.js, packages/client/src/components/AccountSideBar/AccountSideBar.jsx, packages/client/src/components/DragAndDrop/DragAndDrop.jsx, packages/client/src/components/Input/Input.jsx, packages/client/src/pages/Public/Account/Account.jsx, packages/client/src/pages/Public/Reauthenticate/Reauthenticate.jsx, packages/client/src/redux/user/state.js
=> Tech/sprint 4/262/google auth change password

packages/client/src/App.js, packages/client/src/components/TrackCard/TrackCard.jsx
=> fix: delete song in queue page

packages/client/src/App.js, packages/client/src/components/TrackCard/TrackCard.jsx, packages/client/src/components/TrackList/TrackList.jsx
=> Bugs/sprint 4/267/player appers in list order

packages/client/src/api/playlists-api.js, packages/client/src/components/MusicPlayer/MusicPlayer.jsx, packages/client/src/components/TrackCard/TrackCard.jsx, packages/client/src/pages/Public/CreatePlaylist/CreatePlaylist.jsx, packages/client/src/pages/Public/PlaylistUpdate/PlaylistUpdate.jsx, packages/client/src/pages/Public/SinglePlaylist/SinglePlaylist.jsx, packages/client/src/pages/Public/UserView/UserView.jsx, packages/server/src/controllers/account-controller.js, packages/server/src/controllers/album-controller.js, packages/server/src/controllers/auth-controller.js, packages/server/src/controllers/genre-controller.js, packages/server/src/controllers/me-controller.js, packages/server/src/controllers/playlists-controller.js, packages/server/src/controllers/search-controller.js, packages/server/src/controllers/track-controller.js, packages/server/src/controllers/users-controller.js
closes #276 and closes #242 (debounce)
- Fixes add to playlist from trackcard wrong position
- Deleted <hr /> from trackcard
- Updated private playlist toggle in update playlist view
- Fixes fetching private playlist
=> Tech/sprint 5/276/refactor controllers

package.json, packages/client/package.json, packages/server/package.json, packages/server/src/controllers/genre-controller.js, packages/server/src/services/statistics/wave-stats.js
=> Tech/sprint 5/303/fill genres popularity

packages/client/src/components/Router/Router.jsx, packages/client/src/components/UserWave/UserWave.jsx, packages/client/src/pages/Public/UserAlbums/UserAlbums.jsx, packages/client/src/pages/Public/UserPlaylists/UserPlaylists.jsx, packages/client/src/pages/Public/UserTracks/UserTracks.jsx, packages/client/src/pages/Public/UserTracks/index.js
- Added user tracks view
- Added lazy scrolling to: UserTracks, UserAlbums, UserPlaylists
closes #300
=> Users management/tracks view/300/main

packages/client/src/components/AlbumCard/AlbumCard.jsx, packages/client/src/components/AlbumCard/AlbumCard.scss, packages/client/src/components/Header/Header.jsx, packages/client/src/components/Input/Input.jsx, packages/client/src/components/MusicPlayer/MusicPlayer.jsx, packages/client/src/components/MusicPlayer/MusicPlayer.scss, packages/client/src/components/PlaylistCard/PlaylistCard.jsx, packages/client/src/components/PlaylistCard/PlaylistCard.scss, packages/client/src/sass/components/_spacing.scss
=> feat: added hover and transitions to album and playlist cards

packages/client/src/__mocks__/intersectionObserverMock.js, packages/client/src/__test__/app.test.js, packages/client/src/__test__/components/input.test.js, packages/client/src/__test__/pages/home.test.js, packages/client/src/__test__/pages/tracks.test.js, packages/client/src/pages/Public/Reauthenticate/Reauthenticate.jsx, packages/client/src/pages/Public/UpdatePassword/UpdatePassword.jsx, packages/client/src/services/auth/auth.js, packages/server/package.json, packages/server/src/controllers/account-controller.js, packages/server/src/controllers/auth-controller.js
=> Bugs/sprint 5/301/click multiple times upload
